name: Generate Feeds

on:
  schedule:
    - cron: "0 */12 * * *"   # 2 fois par jour
  workflow_dispatch:          # Permet de le lancer manuellement aussi
  push:
    branches: [ main, kafiagy-patch-3 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Feed me up, Scotty
        run: npm install feed-me-up-scotty

      - name: Generate feeds
        run: npx feed-me-up-scotty

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./feeds
          publish_branch: gh-pages
